// Generated by generate_hls_headers.py. Do not edit.
#pragma once

#include <cstdint>

namespace episepset_5k {
inline constexpr int kChannels = 17;
inline constexpr int kSamples = 512;
inline constexpr int kTemporalChannels = 51;
inline constexpr int kSpatialChannels = 32;
inline constexpr int kTemporalKernel = 31;
inline constexpr int kRefinementKernel = 15;
inline constexpr int kPool = 4;
inline constexpr int kPooledSamples = 128;
inline constexpr int kFinalSamples = 32;
inline constexpr std::int64_t kInt16Limit = 32767;
inline constexpr const char* kManifestSha256 = "ca5270a18599c1c5e3c4bacb0891062765da7c8dc0182d795b856afa8d662b40";
inline constexpr const char* kCheckpointSha256 = "c55b430b00deb5b67b92fb36f7208e89d629fb5f6c8f5e2b41180f69cb3b91f8";
inline constexpr double kInputScale = 0.00070522235122137222;
inline constexpr double kTemporalScale = 0.0010317301449676885;
inline constexpr double kSpatialScale = 0.00049781915735280899;
inline constexpr double kRefineDepthwiseScale = 0.00022302165904429142;
inline constexpr double kRefineScale = 0.00041179471876411181;
inline constexpr double kTemporalWeightScale = 4.0460619523497805e-05;
inline constexpr double kSpatialWeightScale = 2.1672757809099636e-05;
inline constexpr double kRefineDepthwiseWeightScale = 1.0885463103051261e-05;
inline constexpr double kRefinePointwiseWeightScale = 7.7239594002735125e-05;
inline constexpr double kClassifierWeightScale = 1.1927067322148488e-05;
inline constexpr double kTemporalRequantRatio = 2.7656198058580615e-05;
inline constexpr double kSpatialRequantRatio = 4.4916788006181379e-05;
inline constexpr double kRefineDepthwiseRequantRatio = 2.429805290023368e-05;
inline constexpr double kRefinePointwiseRequantRatio = 4.1831771058397456e-05;
inline constexpr int kRequantShift = 31;
inline constexpr std::int32_t kTemporalRequantMultiplierQ31 = 59391;
inline constexpr std::int32_t kSpatialRequantMultiplierQ31 = 96458;
inline constexpr std::int32_t kRefineDepthwiseRequantMultiplierQ31 = 52180;
inline constexpr std::int32_t kRefinePointwiseRequantMultiplierQ31 = 89833;
}  // namespace episepset_5k
