"""Generate immutable C/C++ constants from the frozen EpiSepNet-5K package."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import struct


ROOT = Path(__file__).resolve().parents[3]
DEFAULT_PACKAGE = ROOT / "reference_run_21_int16"
DEFAULT_INCLUDE = Path(__file__).resolve().parents[1] / "hls" / "include"

TENSORS = (
    ("temporal_depthwise_weight", "h", 2, (51, 1, 31), (51, 31)),
    ("temporal_depthwise_bias", "i", 4, (51,), (51,)),
    ("spatial_pointwise_weight", "h", 2, (32, 51, 1), (32, 51)),
    ("spatial_pointwise_bias", "i", 4, (32,), (32,)),
    ("refine_depthwise_weight", "h", 2, (32, 1, 15), (32, 15)),
    ("refine_pointwise_weight", "h", 2, (32, 32, 1), (32, 32)),
    ("refine_pointwise_bias", "i", 4, (32,), (32,)),
    ("classifier_weight", "h", 2, (2, 32), (2, 32)),
    ("classifier_bias", "i", 4, (2,), (2,)),
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def element_count(shape: tuple[int, ...]) -> int:
    result = 1
    for dimension in shape:
        result *= dimension
    return result


def format_array(name: str, values: list[int], byte_width: int, shape: tuple[int, ...]) -> str:
    cpp_type = "std::int16_t" if byte_width == 2 else "std::int32_t"
    dimensions = "".join(f"[{dimension}]" for dimension in shape)
    chunks = [", ".join(str(value) for value in values[index:index + 12]) for index in range(0, len(values), 12)]
    body = ",\n    ".join(chunks)
    return f"inline constexpr {cpp_type} {name}{dimensions} = {{\n    {body}\n}};\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--package", type=Path, default=DEFAULT_PACKAGE)
    parser.add_argument("--include", type=Path, default=DEFAULT_INCLUDE)
    args = parser.parse_args()

    package = args.package.resolve()
    include = args.include.resolve()
    manifest_path = package / "model_manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest["architecture"] != "separable_1dcnn" or manifest["parameter_count"] != 5013:
        raise ValueError("The source package is not the frozen EpiSepNet-5K contract")
    if manifest["input"]["shape"] != [1, 17, 512]:
        raise ValueError("Unexpected accelerator input shape")

    metadata = {item["name"]: item for item in manifest["tensors"]}
    arrays: dict[str, tuple[list[int], int, tuple[int, ...]]] = {}
    for name, format_character, byte_width, manifest_shape, c_shape in TENSORS:
        item = metadata.get(name)
        if item is None or item["shape"] != list(manifest_shape):
            raise ValueError(f"Manifest shape mismatch for {name}")
        tensor_path = package / item["path"]
        raw = tensor_path.read_bytes()
        expected_count = element_count(c_shape)
        if len(raw) != expected_count * byte_width:
            raise ValueError(f"Tensor byte count mismatch for {name}")
        values = list(struct.unpack(f"<{expected_count}{format_character}", raw))
        arrays[name] = (values, byte_width, c_shape)

    tensor_scales = {item["name"]: item.get("scale") for item in manifest["tensors"]}
    activation_scales = manifest["activation_scales"]
    ratios = {
        "temporal": activation_scales["input"] * tensor_scales["temporal_depthwise_weight"] / activation_scales["temporal_relu"],
        "spatial": activation_scales["temporal_relu"] * tensor_scales["spatial_pointwise_weight"] / activation_scales["spatial_relu"],
        "refine_depthwise": activation_scales["spatial_relu"] * tensor_scales["refine_depthwise_weight"] / activation_scales["refine_depthwise"],
        "refine_pointwise": activation_scales["refine_depthwise"] * tensor_scales["refine_pointwise_weight"] / activation_scales["refine_relu"],
    }
    q31_multipliers = {name: round(ratio * (1 << 31)) for name, ratio in ratios.items()}

    include.mkdir(parents=True, exist_ok=True)
    config = include / "episepset_5k_contract.h"
    config.write_text(
        "// Generated by generate_hls_headers.py. Do not edit.\n"
        "#pragma once\n\n#include <cstdint>\n\nnamespace episepset_5k {\n"
        "inline constexpr int kChannels = 17;\n"
        "inline constexpr int kSamples = 512;\n"
        "inline constexpr int kTemporalChannels = 51;\n"
        "inline constexpr int kSpatialChannels = 32;\n"
        "inline constexpr int kTemporalKernel = 31;\n"
        "inline constexpr int kRefinementKernel = 15;\n"
        "inline constexpr int kPool = 4;\n"
        "inline constexpr int kPooledSamples = 128;\n"
        "inline constexpr int kFinalSamples = 32;\n"
        "inline constexpr std::int64_t kInt16Limit = 32767;\n"
        f"inline constexpr const char* kManifestSha256 = \"{sha256(manifest_path)}\";\n"
        f"inline constexpr const char* kCheckpointSha256 = \"{manifest['checkpoint_sha256']}\";\n"
        f"inline constexpr double kInputScale = {activation_scales['input']:.17g};\n"
        f"inline constexpr double kTemporalScale = {activation_scales['temporal_relu']:.17g};\n"
        f"inline constexpr double kSpatialScale = {activation_scales['spatial_relu']:.17g};\n"
        f"inline constexpr double kRefineDepthwiseScale = {activation_scales['refine_depthwise']:.17g};\n"
        f"inline constexpr double kRefineScale = {activation_scales['refine_relu']:.17g};\n"
        f"inline constexpr double kTemporalWeightScale = {tensor_scales['temporal_depthwise_weight']:.17g};\n"
        f"inline constexpr double kSpatialWeightScale = {tensor_scales['spatial_pointwise_weight']:.17g};\n"
        f"inline constexpr double kRefineDepthwiseWeightScale = {tensor_scales['refine_depthwise_weight']:.17g};\n"
        f"inline constexpr double kRefinePointwiseWeightScale = {tensor_scales['refine_pointwise_weight']:.17g};\n"
        f"inline constexpr double kClassifierWeightScale = {tensor_scales['classifier_weight']:.17g};\n"
        f"inline constexpr double kTemporalRequantRatio = {ratios['temporal']:.17g};\n"
        f"inline constexpr double kSpatialRequantRatio = {ratios['spatial']:.17g};\n"
        f"inline constexpr double kRefineDepthwiseRequantRatio = {ratios['refine_depthwise']:.17g};\n"
        f"inline constexpr double kRefinePointwiseRequantRatio = {ratios['refine_pointwise']:.17g};\n"
        "inline constexpr int kRequantShift = 31;\n"
        f"inline constexpr std::int32_t kTemporalRequantMultiplierQ31 = {q31_multipliers['temporal']};\n"
        f"inline constexpr std::int32_t kSpatialRequantMultiplierQ31 = {q31_multipliers['spatial']};\n"
        f"inline constexpr std::int32_t kRefineDepthwiseRequantMultiplierQ31 = {q31_multipliers['refine_depthwise']};\n"
        f"inline constexpr std::int32_t kRefinePointwiseRequantMultiplierQ31 = {q31_multipliers['refine_pointwise']};\n"
        "}  // namespace episepset_5k\n",
        encoding="utf-8",
    )
    weights = include / "episepset_5k_weights.h"
    weights.write_text(
        "// Generated by generate_hls_headers.py from the frozen INT16 package. Do not edit.\n"
        "#pragma once\n\n#include <cstdint>\n\nnamespace episepset_5k {\n\n"
        + "\n".join(format_array(name, values, byte_width, shape) for name, (values, byte_width, shape) in arrays.items())
        + "\n}  // namespace episepset_5k\n",
        encoding="utf-8",
    )
    print(f"Generated {config}")
    print(f"Generated {weights}")
    print(f"manifest_sha256={sha256(manifest_path)}")


if __name__ == "__main__":
    main()
